package com.dl.reporting.execution2005;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * The Reporting Services Execution Service enables report execution
 *
 * This class was generated by Apache CXF 3.5.5
 * 2023-10-05T19:39:03.078+05:30
 * Generated source version: 3.5.5
 *
 */
@WebServiceClient(name = "ReportExecutionService",
                  wsdlLocation = "file:/C:/Users/pbirs.service/Downloads/ReportExecution2005.wsdl.xml",
                  targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
public class ReportExecutionService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", "ReportExecutionService");
    public final static QName ReportExecutionServiceSoap = new QName("http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", "ReportExecutionServiceSoap");
    public final static QName ReportExecutionServiceSoap12 = new QName("http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", "ReportExecutionServiceSoap12");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/pbirs.service/Downloads/ReportExecution2005.wsdl.xml");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ReportExecutionService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/pbirs.service/Downloads/ReportExecution2005.wsdl.xml");
        }
        WSDL_LOCATION = url;
    }

    public ReportExecutionService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ReportExecutionService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ReportExecutionService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ReportExecutionService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ReportExecutionService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ReportExecutionService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ReportExecutionServiceSoap
     */
    @WebEndpoint(name = "ReportExecutionServiceSoap")
    public ReportExecutionServiceSoap getReportExecutionServiceSoap() {
        return super.getPort(ReportExecutionServiceSoap, ReportExecutionServiceSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ReportExecutionServiceSoap
     */
    @WebEndpoint(name = "ReportExecutionServiceSoap")
    public ReportExecutionServiceSoap getReportExecutionServiceSoap(WebServiceFeature... features) {
        return super.getPort(ReportExecutionServiceSoap, ReportExecutionServiceSoap.class, features);
    }


    /**
     *
     * @return
     *     returns ReportExecutionServiceSoap
     */
    @WebEndpoint(name = "ReportExecutionServiceSoap12")
    public ReportExecutionServiceSoap getReportExecutionServiceSoap12() {
        return super.getPort(ReportExecutionServiceSoap12, ReportExecutionServiceSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ReportExecutionServiceSoap
     */
    @WebEndpoint(name = "ReportExecutionServiceSoap12")
    public ReportExecutionServiceSoap getReportExecutionServiceSoap12(WebServiceFeature... features) {
        return super.getPort(ReportExecutionServiceSoap12, ReportExecutionServiceSoap.class, features);
    }

}
