
package com.dl.reporting.execution2005;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.5
 * 2023-10-05T19:39:02.820+05:30
 * Generated source version: 3.5.5
 *
 */
public final class ReportExecutionServiceSoap_ReportExecutionServiceSoap_Client {

    private static final QName SERVICE_NAME = new QName("http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", "ReportExecutionService");

    private ReportExecutionServiceSoap_ReportExecutionServiceSoap_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ReportExecutionService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        ReportExecutionService ss = new ReportExecutionService(wsdlURL, SERVICE_NAME);
        ReportExecutionServiceSoap port = ss.getReportExecutionServiceSoap();

        {
        System.out.println("Invoking render2...");
        java.lang.String _render2_format = "";
        java.lang.String _render2_deviceInfo = "";
        com.dl.reporting.execution2005.PageCountMode _render2_paginationMode = null;
        com.dl.reporting.execution2005.ExecutionHeader _render2_executionHeader = null;
        com.dl.reporting.execution2005.TrustedUserHeader _render2_trustedUserHeader = null;
        javax.xml.ws.Holder<byte[]> _render2_result = new javax.xml.ws.Holder<byte[]>();
        javax.xml.ws.Holder<java.lang.String> _render2_extension = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<java.lang.String> _render2_mimeType = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<java.lang.String> _render2_encoding = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<com.dl.reporting.execution2005.ArrayOfWarning> _render2_warnings = new javax.xml.ws.Holder<com.dl.reporting.execution2005.ArrayOfWarning>();
        javax.xml.ws.Holder<com.dl.reporting.execution2005.ArrayOfString> _render2_streamIds = new javax.xml.ws.Holder<com.dl.reporting.execution2005.ArrayOfString>();
        javax.xml.ws.Holder<com.dl.reporting.execution2005.ServerInfoHeader> _render2_serverInfoHeader = new javax.xml.ws.Holder<com.dl.reporting.execution2005.ServerInfoHeader>();
        port.render2(_render2_format, _render2_deviceInfo, _render2_paginationMode, _render2_executionHeader, _render2_trustedUserHeader, _render2_result, _render2_extension, _render2_mimeType, _render2_encoding, _render2_warnings, _render2_streamIds, _render2_serverInfoHeader);

        System.out.println("render2._render2_result=" + _render2_result.value);
        System.out.println("render2._render2_extension=" + _render2_extension.value);
        System.out.println("render2._render2_mimeType=" + _render2_mimeType.value);
        System.out.println("render2._render2_encoding=" + _render2_encoding.value);
        System.out.println("render2._render2_warnings=" + _render2_warnings.value);
        System.out.println("render2._render2_streamIds=" + _render2_streamIds.value);
        System.out.println("render2._render2_serverInfoHeader=" + _render2_serverInfoHeader.value);

        }
        {
        System.out.println("Invoking getRenderResource...");
        java.lang.String _getRenderResource_format = "";
        java.lang.String _getRenderResource_deviceInfo = "";
        com.dl.reporting.execution2005.TrustedUserHeader _getRenderResource_trustedUserHeader = null;
        javax.xml.ws.Holder<byte[]> _getRenderResource_result = new javax.xml.ws.Holder<byte[]>();
        javax.xml.ws.Holder<java.lang.String> _getRenderResource_mimeType = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<com.dl.reporting.execution2005.ServerInfoHeader> _getRenderResource_serverInfoHeader = new javax.xml.ws.Holder<com.dl.reporting.execution2005.ServerInfoHeader>();
        port.getRenderResource(_getRenderResource_format, _getRenderResource_deviceInfo, _getRenderResource_trustedUserHeader, _getRenderResource_result, _getRenderResource_mimeType, _getRenderResource_serverInfoHeader);

        System.out.println("getRenderResource._getRenderResource_result=" + _getRenderResource_result.value);
        System.out.println("getRenderResource._getRenderResource_mimeType=" + _getRenderResource_mimeType.value);
        System.out.println("getRenderResource._getRenderResource_serverInfoHeader=" + _getRenderResource_serverInfoHeader.value);

        }
        {
        System.out.println("Invoking setExecutionParameters2...");
        com.dl.reporting.execution2005.ArrayOfParameterValue _setExecutionParameters2_parameters = null;
        java.lang.String _setExecutionParameters2_parameterLanguage = "";
        com.dl.reporting.execution2005.ExecutionHeader _setExecutionParameters2_executionHeader = null;
        com.dl.reporting.execution2005.TrustedUserHeader _setExecutionParameters2_trustedUserHeader = null;
        javax.xml.ws.Holder<com.dl.reporting.execution2005.ServerInfoHeader> _setExecutionParameters2_serverInfoHeader = new javax.xml.ws.Holder<com.dl.reporting.execution2005.ServerInfoHeader>();
        com.dl.reporting.execution2005.ExecutionInfo2 _setExecutionParameters2__return = port.setExecutionParameters2(_setExecutionParameters2_parameters, _setExecutionParameters2_parameterLanguage, _setExecutionParameters2_executionHeader, _setExecutionParameters2_trustedUserHeader, _setExecutionParameters2_serverInfoHeader);
        System.out.println("setExecutionParameters2.result=" + _setExecutionParameters2__return);

        System.out.println("setExecutionParameters2._setExecutionParameters2_serverInfoHeader=" + _setExecutionParameters2_serverInfoHeader.value);

        }
        {
        System.out.println("Invoking setExecutionParameters3...");
        com.dl.reporting.execution2005.ArrayOfParameterValue _setExecutionParameters3_parameters = null;
        java.lang.String _setExecutionParameters3_parameterLanguage = "";
        com.dl.reporting.execution2005.ExecutionHeader _setExecutionParameters3_executionHeader = null;
        com.dl.reporting.execution2005.TrustedUserHeader _setExecutionParameters3_trustedUserHeader = null;
        javax.xml.ws.Holder<com.dl.reporting.execution2005.ServerInfoHeader> _setExecutionParameters3_serverInfoHeader = new javax.xml.ws.Holder<com.dl.reporting.execution2005.ServerInfoHeader>();
        com.dl.reporting.execution2005.ExecutionInfo3 _setExecutionParameters3__return = port.setExecutionParameters3(_setExecutionParameters3_parameters, _setExecutionParameters3_parameterLanguage, _setExecutionParameters3_executionHeader, _setExecutionParameters3_trustedUserHeader, _setExecutionParameters3_serverInfoHeader);
        System.out.println("setExecutionParameters3.result=" + _setExecutionParameters3__return);

        System.out.println("setExecutionParameters3._setExecutionParameters3_serverInfoHeader=" + _setExecutionParameters3_serverInfoHeader.value);

        }
        {
        System.out.println("Invoking loadDrillthroughTarget...");
        java.lang.String _loadDrillthroughTarget_drillthroughID = "";
        com.dl.reporting.execution2005.ExecutionHeader _loadDrillthroughTarget_executionHeaderVal = null;
        javax.xml.ws.Holder<com.dl.reporting.execution2005.ExecutionHeader> _loadDrillthroughTarget_executionHeader = new javax.xml.ws.Holder<com.dl.reporting.execution2005.ExecutionHeader>(_loadDrillthroughTarget_executionHeaderVal);
        com.dl.reporting.execution2005.TrustedUserHeader _loadDrillthroughTarget_trustedUserHeader = null;
        javax.xml.ws.Holder<com.dl.reporting.execution2005.ServerInfoHeader> _loadDrillthroughTarget_serverInfoHeader = new javax.xml.ws.Holder<com.dl.reporting.execution2005.ServerInfoHeader>();
        com.dl.reporting.execution2005.ExecutionInfo _loadDrillthroughTarget__return = port.loadDrillthroughTarget(_loadDrillthroughTarget_drillthroughID, _loadDrillthroughTarget_executionHeader, _loadDrillthroughTarget_trustedUserHeader, _loadDrillthroughTarget_serverInfoHeader);
        System.out.println("loadDrillthroughTarget.result=" + _loadDrillthroughTarget__return);

        System.out.println("loadDrillthroughTarget._loadDrillthroughTarget_executionHeader=" + _loadDrillthroughTarget_executionHeader.value);
        System.out.println("loadDrillthroughTarget._loadDrillthroughTarget_serverInfoHeader=" + _loadDrillthroughTarget_serverInfoHeader.value);

        }
        {
        System.out.println("Invoking getDocumentMap...");
        com.dl.reporting.execution2005.ExecutionHeader _getDocumentMap_executionHeader = null;
        com.dl.reporting.execution2005.TrustedUserHeader _getDocumentMap_trustedUserHeader = null;
        javax.xml.ws.Holder<com.dl.reporting.execution2005.ServerInfoHeader> _getDocumentMap_serverInfoHeader = new javax.xml.ws.Holder<com.dl.reporting.execution2005.ServerInfoHeader>();
        com.dl.reporting.execution2005.DocumentMapNode _getDocumentMap__return = port.getDocumentMap(_getDocumentMap_executionHeader, _getDocumentMap_trustedUserHeader, _getDocumentMap_serverInfoHeader);
        System.out.println("getDocumentMap.result=" + _getDocumentMap__return);

        System.out.println("getDocumentMap._getDocumentMap_serverInfoHeader=" + _getDocumentMap_serverInfoHeader.value);

        }
        {
        System.out.println("Invoking listRenderingExtensions...");
        com.dl.reporting.execution2005.TrustedUserHeader _listRenderingExtensions_trustedUserHeader = null;
        javax.xml.ws.Holder<com.dl.reporting.execution2005.ServerInfoHeader> _listRenderingExtensions_serverInfoHeader = new javax.xml.ws.Holder<com.dl.reporting.execution2005.ServerInfoHeader>();
        com.dl.reporting.execution2005.ArrayOfExtension _listRenderingExtensions__return = port.listRenderingExtensions(_listRenderingExtensions_trustedUserHeader, _listRenderingExtensions_serverInfoHeader);
        System.out.println("listRenderingExtensions.result=" + _listRenderingExtensions__return);

        System.out.println("listRenderingExtensions._listRenderingExtensions_serverInfoHeader=" + _listRenderingExtensions_serverInfoHeader.value);

        }
        {
        System.out.println("Invoking listSecureMethods...");
        com.dl.reporting.execution2005.TrustedUserHeader _listSecureMethods_trustedUserHeader = null;
        javax.xml.ws.Holder<com.dl.reporting.execution2005.ServerInfoHeader> _listSecureMethods_serverInfoHeader = new javax.xml.ws.Holder<com.dl.reporting.execution2005.ServerInfoHeader>();
        com.dl.reporting.execution2005.ArrayOfString _listSecureMethods__return = port.listSecureMethods(_listSecureMethods_trustedUserHeader, _listSecureMethods_serverInfoHeader);
        System.out.println("listSecureMethods.result=" + _listSecureMethods__return);

        System.out.println("listSecureMethods._listSecureMethods_serverInfoHeader=" + _listSecureMethods_serverInfoHeader.value);

        }
        {
        System.out.println("Invoking resetExecution3...");
        com.dl.reporting.execution2005.ExecutionHeader _resetExecution3_executionHeader = null;
        com.dl.reporting.execution2005.TrustedUserHeader _resetExecution3_trustedUserHeader = null;
        javax.xml.ws.Holder<com.dl.reporting.execution2005.ServerInfoHeader> _resetExecution3_serverInfoHeader = new javax.xml.ws.Holder<com.dl.reporting.execution2005.ServerInfoHeader>();
        com.dl.reporting.execution2005.ExecutionInfo3 _resetExecution3__return = port.resetExecution3(_resetExecution3_executionHeader, _resetExecution3_trustedUserHeader, _resetExecution3_serverInfoHeader);
        System.out.println("resetExecution3.result=" + _resetExecution3__return);

        System.out.println("resetExecution3._resetExecution3_serverInfoHeader=" + _resetExecution3_serverInfoHeader.value);

        }
        {
        System.out.println("Invoking setExecutionParameters...");
        com.dl.reporting.execution2005.ArrayOfParameterValue _setExecutionParameters_parameters = null;
        java.lang.String _setExecutionParameters_parameterLanguage = "";
        com.dl.reporting.execution2005.ExecutionHeader _setExecutionParameters_executionHeader = null;
        com.dl.reporting.execution2005.TrustedUserHeader _setExecutionParameters_trustedUserHeader = null;
        javax.xml.ws.Holder<com.dl.reporting.execution2005.ServerInfoHeader> _setExecutionParameters_serverInfoHeader = new javax.xml.ws.Holder<com.dl.reporting.execution2005.ServerInfoHeader>();
        com.dl.reporting.execution2005.ExecutionInfo _setExecutionParameters__return = port.setExecutionParameters(_setExecutionParameters_parameters, _setExecutionParameters_parameterLanguage, _setExecutionParameters_executionHeader, _setExecutionParameters_trustedUserHeader, _setExecutionParameters_serverInfoHeader);
        System.out.println("setExecutionParameters.result=" + _setExecutionParameters__return);

        System.out.println("setExecutionParameters._setExecutionParameters_serverInfoHeader=" + _setExecutionParameters_serverInfoHeader.value);

        }
        {
        System.out.println("Invoking deliverReportItem...");
        java.lang.String _deliverReportItem_format = "";
        java.lang.String _deliverReportItem_deviceInfo = "";
        com.dl.reporting.execution2005.ExtensionSettings _deliverReportItem_extensionSettings = null;
        java.lang.String _deliverReportItem_description = "";
        java.lang.String _deliverReportItem_eventType = "";
        java.lang.String _deliverReportItem_matchData = "";
        com.dl.reporting.execution2005.ExecutionHeader _deliverReportItem_executionHeader = null;
        com.dl.reporting.execution2005.TrustedUserHeader _deliverReportItem_trustedUserHeader = null;
        javax.xml.ws.Holder<com.dl.reporting.execution2005.ServerInfoHeader> _deliverReportItem_serverInfoHeader = new javax.xml.ws.Holder<com.dl.reporting.execution2005.ServerInfoHeader>();
        port.deliverReportItem(_deliverReportItem_format, _deliverReportItem_deviceInfo, _deliverReportItem_extensionSettings, _deliverReportItem_description, _deliverReportItem_eventType, _deliverReportItem_matchData, _deliverReportItem_executionHeader, _deliverReportItem_trustedUserHeader, _deliverReportItem_serverInfoHeader);

        System.out.println("deliverReportItem._deliverReportItem_serverInfoHeader=" + _deliverReportItem_serverInfoHeader.value);

        }
        {
        System.out.println("Invoking resetExecution2...");
        com.dl.reporting.execution2005.ExecutionHeader _resetExecution2_executionHeader = null;
        com.dl.reporting.execution2005.TrustedUserHeader _resetExecution2_trustedUserHeader = null;
        javax.xml.ws.Holder<com.dl.reporting.execution2005.ServerInfoHeader> _resetExecution2_serverInfoHeader = new javax.xml.ws.Holder<com.dl.reporting.execution2005.ServerInfoHeader>();
        com.dl.reporting.execution2005.ExecutionInfo2 _resetExecution2__return = port.resetExecution2(_resetExecution2_executionHeader, _resetExecution2_trustedUserHeader, _resetExecution2_serverInfoHeader);
        System.out.println("resetExecution2.result=" + _resetExecution2__return);

        System.out.println("resetExecution2._resetExecution2_serverInfoHeader=" + _resetExecution2_serverInfoHeader.value);

        }
        {
        System.out.println("Invoking sort2...");
        java.lang.String _sort2_sortItem = "";
        com.dl.reporting.execution2005.SortDirectionEnum _sort2_direction = null;
        boolean _sort2_clear = false;
        com.dl.reporting.execution2005.PageCountMode _sort2_paginationMode = null;
        com.dl.reporting.execution2005.ExecutionHeader _sort2_executionHeader = null;
        com.dl.reporting.execution2005.TrustedUserHeader _sort2_trustedUserHeader = null;
        javax.xml.ws.Holder<java.lang.Integer> _sort2_pageNumber = new javax.xml.ws.Holder<java.lang.Integer>();
        javax.xml.ws.Holder<java.lang.String> _sort2_reportItem = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<com.dl.reporting.execution2005.ExecutionInfo2> _sort2_executionInfo = new javax.xml.ws.Holder<com.dl.reporting.execution2005.ExecutionInfo2>();
        javax.xml.ws.Holder<com.dl.reporting.execution2005.ServerInfoHeader> _sort2_serverInfoHeader = new javax.xml.ws.Holder<com.dl.reporting.execution2005.ServerInfoHeader>();
        port.sort2(_sort2_sortItem, _sort2_direction, _sort2_clear, _sort2_paginationMode, _sort2_executionHeader, _sort2_trustedUserHeader, _sort2_pageNumber, _sort2_reportItem, _sort2_executionInfo, _sort2_serverInfoHeader);

        System.out.println("sort2._sort2_pageNumber=" + _sort2_pageNumber.value);
        System.out.println("sort2._sort2_reportItem=" + _sort2_reportItem.value);
        System.out.println("sort2._sort2_executionInfo=" + _sort2_executionInfo.value);
        System.out.println("sort2._sort2_serverInfoHeader=" + _sort2_serverInfoHeader.value);

        }
        {
        System.out.println("Invoking navigateBookmark...");
        java.lang.String _navigateBookmark_bookmarkID = "";
        com.dl.reporting.execution2005.ExecutionHeader _navigateBookmark_executionHeader = null;
        com.dl.reporting.execution2005.TrustedUserHeader _navigateBookmark_trustedUserHeader = null;
        javax.xml.ws.Holder<java.lang.Integer> _navigateBookmark_pageNumber = new javax.xml.ws.Holder<java.lang.Integer>();
        javax.xml.ws.Holder<java.lang.String> _navigateBookmark_uniqueName = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<com.dl.reporting.execution2005.ServerInfoHeader> _navigateBookmark_serverInfoHeader = new javax.xml.ws.Holder<com.dl.reporting.execution2005.ServerInfoHeader>();
        port.navigateBookmark(_navigateBookmark_bookmarkID, _navigateBookmark_executionHeader, _navigateBookmark_trustedUserHeader, _navigateBookmark_pageNumber, _navigateBookmark_uniqueName, _navigateBookmark_serverInfoHeader);

        System.out.println("navigateBookmark._navigateBookmark_pageNumber=" + _navigateBookmark_pageNumber.value);
        System.out.println("navigateBookmark._navigateBookmark_uniqueName=" + _navigateBookmark_uniqueName.value);
        System.out.println("navigateBookmark._navigateBookmark_serverInfoHeader=" + _navigateBookmark_serverInfoHeader.value);

        }
        {
        System.out.println("Invoking sort3...");
        java.lang.String _sort3_sortItem = "";
        com.dl.reporting.execution2005.SortDirectionEnum _sort3_direction = null;
        boolean _sort3_clear = false;
        com.dl.reporting.execution2005.PageCountMode _sort3_paginationMode = null;
        com.dl.reporting.execution2005.ExecutionHeader _sort3_executionHeader = null;
        com.dl.reporting.execution2005.TrustedUserHeader _sort3_trustedUserHeader = null;
        javax.xml.ws.Holder<java.lang.Integer> _sort3_pageNumber = new javax.xml.ws.Holder<java.lang.Integer>();
        javax.xml.ws.Holder<java.lang.String> _sort3_reportItem = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<com.dl.reporting.execution2005.ExecutionInfo3> _sort3_executionInfo = new javax.xml.ws.Holder<com.dl.reporting.execution2005.ExecutionInfo3>();
        javax.xml.ws.Holder<com.dl.reporting.execution2005.ServerInfoHeader> _sort3_serverInfoHeader = new javax.xml.ws.Holder<com.dl.reporting.execution2005.ServerInfoHeader>();
        port.sort3(_sort3_sortItem, _sort3_direction, _sort3_clear, _sort3_paginationMode, _sort3_executionHeader, _sort3_trustedUserHeader, _sort3_pageNumber, _sort3_reportItem, _sort3_executionInfo, _sort3_serverInfoHeader);

        System.out.println("sort3._sort3_pageNumber=" + _sort3_pageNumber.value);
        System.out.println("sort3._sort3_reportItem=" + _sort3_reportItem.value);
        System.out.println("sort3._sort3_executionInfo=" + _sort3_executionInfo.value);
        System.out.println("sort3._sort3_serverInfoHeader=" + _sort3_serverInfoHeader.value);

        }
        {
        System.out.println("Invoking logoff...");
        javax.xml.ws.Holder<com.dl.reporting.execution2005.ServerInfoHeader> _logoff_serverInfoHeader = new javax.xml.ws.Holder<com.dl.reporting.execution2005.ServerInfoHeader>();
        port.logoff(_logoff_serverInfoHeader);

        System.out.println("logoff._logoff_serverInfoHeader=" + _logoff_serverInfoHeader.value);

        }
        {
        System.out.println("Invoking loadReport...");
        java.lang.String _loadReport_report = "";
        java.lang.String _loadReport_historyID = "";
        com.dl.reporting.execution2005.TrustedUserHeader _loadReport_trustedUserHeader = null;
        javax.xml.ws.Holder<com.dl.reporting.execution2005.ExecutionHeader> _loadReport_executionHeader = new javax.xml.ws.Holder<com.dl.reporting.execution2005.ExecutionHeader>();
        javax.xml.ws.Holder<com.dl.reporting.execution2005.ServerInfoHeader> _loadReport_serverInfoHeader = new javax.xml.ws.Holder<com.dl.reporting.execution2005.ServerInfoHeader>();
        com.dl.reporting.execution2005.ExecutionInfo _loadReport__return = port.loadReport(_loadReport_report, _loadReport_historyID, _loadReport_trustedUserHeader, _loadReport_executionHeader, _loadReport_serverInfoHeader);
        System.out.println("loadReport.result=" + _loadReport__return);

        System.out.println("loadReport._loadReport_executionHeader=" + _loadReport_executionHeader.value);
        System.out.println("loadReport._loadReport_serverInfoHeader=" + _loadReport_serverInfoHeader.value);

        }
        {
        System.out.println("Invoking loadReportDefinition...");
        byte[] _loadReportDefinition_definition = new byte[0];
        com.dl.reporting.execution2005.TrustedUserHeader _loadReportDefinition_trustedUserHeader = null;
        javax.xml.ws.Holder<com.dl.reporting.execution2005.ExecutionInfo> _loadReportDefinition_executionInfo = new javax.xml.ws.Holder<com.dl.reporting.execution2005.ExecutionInfo>();
        javax.xml.ws.Holder<com.dl.reporting.execution2005.ArrayOfWarning> _loadReportDefinition_warnings = new javax.xml.ws.Holder<com.dl.reporting.execution2005.ArrayOfWarning>();
        javax.xml.ws.Holder<com.dl.reporting.execution2005.ExecutionHeader> _loadReportDefinition_executionHeader = new javax.xml.ws.Holder<com.dl.reporting.execution2005.ExecutionHeader>();
        javax.xml.ws.Holder<com.dl.reporting.execution2005.ServerInfoHeader> _loadReportDefinition_serverInfoHeader = new javax.xml.ws.Holder<com.dl.reporting.execution2005.ServerInfoHeader>();
        port.loadReportDefinition(_loadReportDefinition_definition, _loadReportDefinition_trustedUserHeader, _loadReportDefinition_executionInfo, _loadReportDefinition_warnings, _loadReportDefinition_executionHeader, _loadReportDefinition_serverInfoHeader);

        System.out.println("loadReportDefinition._loadReportDefinition_executionInfo=" + _loadReportDefinition_executionInfo.value);
        System.out.println("loadReportDefinition._loadReportDefinition_warnings=" + _loadReportDefinition_warnings.value);
        System.out.println("loadReportDefinition._loadReportDefinition_executionHeader=" + _loadReportDefinition_executionHeader.value);
        System.out.println("loadReportDefinition._loadReportDefinition_serverInfoHeader=" + _loadReportDefinition_serverInfoHeader.value);

        }
        {
        System.out.println("Invoking loadReport2...");
        java.lang.String _loadReport2_report = "";
        java.lang.String _loadReport2_historyID = "";
        com.dl.reporting.execution2005.TrustedUserHeader _loadReport2_trustedUserHeader = null;
        javax.xml.ws.Holder<com.dl.reporting.execution2005.ExecutionHeader> _loadReport2_executionHeader = new javax.xml.ws.Holder<com.dl.reporting.execution2005.ExecutionHeader>();
        javax.xml.ws.Holder<com.dl.reporting.execution2005.ServerInfoHeader> _loadReport2_serverInfoHeader = new javax.xml.ws.Holder<com.dl.reporting.execution2005.ServerInfoHeader>();
        com.dl.reporting.execution2005.ExecutionInfo2 _loadReport2__return = port.loadReport2(_loadReport2_report, _loadReport2_historyID, _loadReport2_trustedUserHeader, _loadReport2_executionHeader, _loadReport2_serverInfoHeader);
        System.out.println("loadReport2.result=" + _loadReport2__return);

        System.out.println("loadReport2._loadReport2_executionHeader=" + _loadReport2_executionHeader.value);
        System.out.println("loadReport2._loadReport2_serverInfoHeader=" + _loadReport2_serverInfoHeader.value);

        }
        {
        System.out.println("Invoking loadReport3...");
        java.lang.String _loadReport3_report = "";
        java.lang.String _loadReport3_historyID = "";
        com.dl.reporting.execution2005.TrustedUserHeader _loadReport3_trustedUserHeader = null;
        javax.xml.ws.Holder<com.dl.reporting.execution2005.ExecutionHeader> _loadReport3_executionHeader = new javax.xml.ws.Holder<com.dl.reporting.execution2005.ExecutionHeader>();
        javax.xml.ws.Holder<com.dl.reporting.execution2005.ServerInfoHeader> _loadReport3_serverInfoHeader = new javax.xml.ws.Holder<com.dl.reporting.execution2005.ServerInfoHeader>();
        com.dl.reporting.execution2005.ExecutionInfo3 _loadReport3__return = port.loadReport3(_loadReport3_report, _loadReport3_historyID, _loadReport3_trustedUserHeader, _loadReport3_executionHeader, _loadReport3_serverInfoHeader);
        System.out.println("loadReport3.result=" + _loadReport3__return);

        System.out.println("loadReport3._loadReport3_executionHeader=" + _loadReport3_executionHeader.value);
        System.out.println("loadReport3._loadReport3_serverInfoHeader=" + _loadReport3_serverInfoHeader.value);

        }
        {
        System.out.println("Invoking loadDrillthroughTarget3...");
        java.lang.String _loadDrillthroughTarget3_drillthroughID = "";
        com.dl.reporting.execution2005.ExecutionHeader _loadDrillthroughTarget3_executionHeaderVal = null;
        javax.xml.ws.Holder<com.dl.reporting.execution2005.ExecutionHeader> _loadDrillthroughTarget3_executionHeader = new javax.xml.ws.Holder<com.dl.reporting.execution2005.ExecutionHeader>(_loadDrillthroughTarget3_executionHeaderVal);
        com.dl.reporting.execution2005.TrustedUserHeader _loadDrillthroughTarget3_trustedUserHeader = null;
        javax.xml.ws.Holder<com.dl.reporting.execution2005.ServerInfoHeader> _loadDrillthroughTarget3_serverInfoHeader = new javax.xml.ws.Holder<com.dl.reporting.execution2005.ServerInfoHeader>();
        com.dl.reporting.execution2005.ExecutionInfo3 _loadDrillthroughTarget3__return = port.loadDrillthroughTarget3(_loadDrillthroughTarget3_drillthroughID, _loadDrillthroughTarget3_executionHeader, _loadDrillthroughTarget3_trustedUserHeader, _loadDrillthroughTarget3_serverInfoHeader);
        System.out.println("loadDrillthroughTarget3.result=" + _loadDrillthroughTarget3__return);

        System.out.println("loadDrillthroughTarget3._loadDrillthroughTarget3_executionHeader=" + _loadDrillthroughTarget3_executionHeader.value);
        System.out.println("loadDrillthroughTarget3._loadDrillthroughTarget3_serverInfoHeader=" + _loadDrillthroughTarget3_serverInfoHeader.value);

        }
        {
        System.out.println("Invoking loadDrillthroughTarget2...");
        java.lang.String _loadDrillthroughTarget2_drillthroughID = "";
        com.dl.reporting.execution2005.ExecutionHeader _loadDrillthroughTarget2_executionHeaderVal = null;
        javax.xml.ws.Holder<com.dl.reporting.execution2005.ExecutionHeader> _loadDrillthroughTarget2_executionHeader = new javax.xml.ws.Holder<com.dl.reporting.execution2005.ExecutionHeader>(_loadDrillthroughTarget2_executionHeaderVal);
        com.dl.reporting.execution2005.TrustedUserHeader _loadDrillthroughTarget2_trustedUserHeader = null;
        javax.xml.ws.Holder<com.dl.reporting.execution2005.ServerInfoHeader> _loadDrillthroughTarget2_serverInfoHeader = new javax.xml.ws.Holder<com.dl.reporting.execution2005.ServerInfoHeader>();
        com.dl.reporting.execution2005.ExecutionInfo2 _loadDrillthroughTarget2__return = port.loadDrillthroughTarget2(_loadDrillthroughTarget2_drillthroughID, _loadDrillthroughTarget2_executionHeader, _loadDrillthroughTarget2_trustedUserHeader, _loadDrillthroughTarget2_serverInfoHeader);
        System.out.println("loadDrillthroughTarget2.result=" + _loadDrillthroughTarget2__return);

        System.out.println("loadDrillthroughTarget2._loadDrillthroughTarget2_executionHeader=" + _loadDrillthroughTarget2_executionHeader.value);
        System.out.println("loadDrillthroughTarget2._loadDrillthroughTarget2_serverInfoHeader=" + _loadDrillthroughTarget2_serverInfoHeader.value);

        }
        {
        System.out.println("Invoking navigateDocumentMap...");
        java.lang.String _navigateDocumentMap_docMapID = "";
        com.dl.reporting.execution2005.ExecutionHeader _navigateDocumentMap_executionHeader = null;
        com.dl.reporting.execution2005.TrustedUserHeader _navigateDocumentMap_trustedUserHeader = null;
        javax.xml.ws.Holder<com.dl.reporting.execution2005.ServerInfoHeader> _navigateDocumentMap_serverInfoHeader = new javax.xml.ws.Holder<com.dl.reporting.execution2005.ServerInfoHeader>();
        int _navigateDocumentMap__return = port.navigateDocumentMap(_navigateDocumentMap_docMapID, _navigateDocumentMap_executionHeader, _navigateDocumentMap_trustedUserHeader, _navigateDocumentMap_serverInfoHeader);
        System.out.println("navigateDocumentMap.result=" + _navigateDocumentMap__return);

        System.out.println("navigateDocumentMap._navigateDocumentMap_serverInfoHeader=" + _navigateDocumentMap_serverInfoHeader.value);

        }
        {
        System.out.println("Invoking setExecutionCredentials3...");
        com.dl.reporting.execution2005.ArrayOfDataSourceCredentials _setExecutionCredentials3_credentials = null;
        com.dl.reporting.execution2005.ExecutionHeader _setExecutionCredentials3_executionHeader = null;
        com.dl.reporting.execution2005.TrustedUserHeader _setExecutionCredentials3_trustedUserHeader = null;
        javax.xml.ws.Holder<com.dl.reporting.execution2005.ServerInfoHeader> _setExecutionCredentials3_serverInfoHeader = new javax.xml.ws.Holder<com.dl.reporting.execution2005.ServerInfoHeader>();
        com.dl.reporting.execution2005.ExecutionInfo3 _setExecutionCredentials3__return = port.setExecutionCredentials3(_setExecutionCredentials3_credentials, _setExecutionCredentials3_executionHeader, _setExecutionCredentials3_trustedUserHeader, _setExecutionCredentials3_serverInfoHeader);
        System.out.println("setExecutionCredentials3.result=" + _setExecutionCredentials3__return);

        System.out.println("setExecutionCredentials3._setExecutionCredentials3_serverInfoHeader=" + _setExecutionCredentials3_serverInfoHeader.value);

        }
        {
        System.out.println("Invoking setExecutionCredentials2...");
        com.dl.reporting.execution2005.ArrayOfDataSourceCredentials _setExecutionCredentials2_credentials = null;
        com.dl.reporting.execution2005.ExecutionHeader _setExecutionCredentials2_executionHeader = null;
        com.dl.reporting.execution2005.TrustedUserHeader _setExecutionCredentials2_trustedUserHeader = null;
        javax.xml.ws.Holder<com.dl.reporting.execution2005.ServerInfoHeader> _setExecutionCredentials2_serverInfoHeader = new javax.xml.ws.Holder<com.dl.reporting.execution2005.ServerInfoHeader>();
        com.dl.reporting.execution2005.ExecutionInfo2 _setExecutionCredentials2__return = port.setExecutionCredentials2(_setExecutionCredentials2_credentials, _setExecutionCredentials2_executionHeader, _setExecutionCredentials2_trustedUserHeader, _setExecutionCredentials2_serverInfoHeader);
        System.out.println("setExecutionCredentials2.result=" + _setExecutionCredentials2__return);

        System.out.println("setExecutionCredentials2._setExecutionCredentials2_serverInfoHeader=" + _setExecutionCredentials2_serverInfoHeader.value);

        }
        {
        System.out.println("Invoking render...");
        java.lang.String _render_format = "";
        java.lang.String _render_deviceInfo = "";
        com.dl.reporting.execution2005.ExecutionHeader _render_executionHeader = null;
        com.dl.reporting.execution2005.TrustedUserHeader _render_trustedUserHeader = null;
        javax.xml.ws.Holder<byte[]> _render_result = new javax.xml.ws.Holder<byte[]>();
        javax.xml.ws.Holder<java.lang.String> _render_extension = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<java.lang.String> _render_mimeType = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<java.lang.String> _render_encoding = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<com.dl.reporting.execution2005.ArrayOfWarning> _render_warnings = new javax.xml.ws.Holder<com.dl.reporting.execution2005.ArrayOfWarning>();
        javax.xml.ws.Holder<com.dl.reporting.execution2005.ArrayOfString> _render_streamIds = new javax.xml.ws.Holder<com.dl.reporting.execution2005.ArrayOfString>();
        javax.xml.ws.Holder<com.dl.reporting.execution2005.ServerInfoHeader> _render_serverInfoHeader = new javax.xml.ws.Holder<com.dl.reporting.execution2005.ServerInfoHeader>();
        port.render(_render_format, _render_deviceInfo, _render_executionHeader, _render_trustedUserHeader, _render_result, _render_extension, _render_mimeType, _render_encoding, _render_warnings, _render_streamIds, _render_serverInfoHeader);

        System.out.println("render._render_result=" + _render_result.value);
        System.out.println("render._render_extension=" + _render_extension.value);
        System.out.println("render._render_mimeType=" + _render_mimeType.value);
        System.out.println("render._render_encoding=" + _render_encoding.value);
        System.out.println("render._render_warnings=" + _render_warnings.value);
        System.out.println("render._render_streamIds=" + _render_streamIds.value);
        System.out.println("render._render_serverInfoHeader=" + _render_serverInfoHeader.value);

        }
        {
        System.out.println("Invoking getExecutionInfo...");
        com.dl.reporting.execution2005.ExecutionHeader _getExecutionInfo_executionHeader = null;
        com.dl.reporting.execution2005.TrustedUserHeader _getExecutionInfo_trustedUserHeader = null;
        javax.xml.ws.Holder<com.dl.reporting.execution2005.ServerInfoHeader> _getExecutionInfo_serverInfoHeader = new javax.xml.ws.Holder<com.dl.reporting.execution2005.ServerInfoHeader>();
        com.dl.reporting.execution2005.ExecutionInfo _getExecutionInfo__return = port.getExecutionInfo(_getExecutionInfo_executionHeader, _getExecutionInfo_trustedUserHeader, _getExecutionInfo_serverInfoHeader);
        System.out.println("getExecutionInfo.result=" + _getExecutionInfo__return);

        System.out.println("getExecutionInfo._getExecutionInfo_serverInfoHeader=" + _getExecutionInfo_serverInfoHeader.value);

        }
        {
        System.out.println("Invoking loadReportDefinition3...");
        byte[] _loadReportDefinition3_definition = new byte[0];
        com.dl.reporting.execution2005.TrustedUserHeader _loadReportDefinition3_trustedUserHeader = null;
        javax.xml.ws.Holder<com.dl.reporting.execution2005.ExecutionInfo3> _loadReportDefinition3_executionInfo = new javax.xml.ws.Holder<com.dl.reporting.execution2005.ExecutionInfo3>();
        javax.xml.ws.Holder<com.dl.reporting.execution2005.ArrayOfWarning> _loadReportDefinition3_warnings = new javax.xml.ws.Holder<com.dl.reporting.execution2005.ArrayOfWarning>();
        javax.xml.ws.Holder<com.dl.reporting.execution2005.ExecutionHeader> _loadReportDefinition3_executionHeader = new javax.xml.ws.Holder<com.dl.reporting.execution2005.ExecutionHeader>();
        javax.xml.ws.Holder<com.dl.reporting.execution2005.ServerInfoHeader> _loadReportDefinition3_serverInfoHeader = new javax.xml.ws.Holder<com.dl.reporting.execution2005.ServerInfoHeader>();
        port.loadReportDefinition3(_loadReportDefinition3_definition, _loadReportDefinition3_trustedUserHeader, _loadReportDefinition3_executionInfo, _loadReportDefinition3_warnings, _loadReportDefinition3_executionHeader, _loadReportDefinition3_serverInfoHeader);

        System.out.println("loadReportDefinition3._loadReportDefinition3_executionInfo=" + _loadReportDefinition3_executionInfo.value);
        System.out.println("loadReportDefinition3._loadReportDefinition3_warnings=" + _loadReportDefinition3_warnings.value);
        System.out.println("loadReportDefinition3._loadReportDefinition3_executionHeader=" + _loadReportDefinition3_executionHeader.value);
        System.out.println("loadReportDefinition3._loadReportDefinition3_serverInfoHeader=" + _loadReportDefinition3_serverInfoHeader.value);

        }
        {
        System.out.println("Invoking findString...");
        int _findString_startPage = 0;
        int _findString_endPage = 0;
        java.lang.String _findString_findValue = "";
        com.dl.reporting.execution2005.ExecutionHeader _findString_executionHeader = null;
        com.dl.reporting.execution2005.TrustedUserHeader _findString_trustedUserHeader = null;
        javax.xml.ws.Holder<com.dl.reporting.execution2005.ServerInfoHeader> _findString_serverInfoHeader = new javax.xml.ws.Holder<com.dl.reporting.execution2005.ServerInfoHeader>();
        int _findString__return = port.findString(_findString_startPage, _findString_endPage, _findString_findValue, _findString_executionHeader, _findString_trustedUserHeader, _findString_serverInfoHeader);
        System.out.println("findString.result=" + _findString__return);

        System.out.println("findString._findString_serverInfoHeader=" + _findString_serverInfoHeader.value);

        }
        {
        System.out.println("Invoking logonUser...");
        java.lang.String _logonUser_userName = "";
        java.lang.String _logonUser_password = "";
        java.lang.String _logonUser_authority = "";
        javax.xml.ws.Holder<com.dl.reporting.execution2005.ServerInfoHeader> _logonUser_serverInfoHeader = new javax.xml.ws.Holder<com.dl.reporting.execution2005.ServerInfoHeader>();
        port.logonUser(_logonUser_userName, _logonUser_password, _logonUser_authority, _logonUser_serverInfoHeader);

        System.out.println("logonUser._logonUser_serverInfoHeader=" + _logonUser_serverInfoHeader.value);

        }
        {
        System.out.println("Invoking toggleItem...");
        java.lang.String _toggleItem_toggleID = "";
        com.dl.reporting.execution2005.ExecutionHeader _toggleItem_executionHeader = null;
        com.dl.reporting.execution2005.TrustedUserHeader _toggleItem_trustedUserHeader = null;
        javax.xml.ws.Holder<com.dl.reporting.execution2005.ServerInfoHeader> _toggleItem_serverInfoHeader = new javax.xml.ws.Holder<com.dl.reporting.execution2005.ServerInfoHeader>();
        boolean _toggleItem__return = port.toggleItem(_toggleItem_toggleID, _toggleItem_executionHeader, _toggleItem_trustedUserHeader, _toggleItem_serverInfoHeader);
        System.out.println("toggleItem.result=" + _toggleItem__return);

        System.out.println("toggleItem._toggleItem_serverInfoHeader=" + _toggleItem_serverInfoHeader.value);

        }
        {
        System.out.println("Invoking sort...");
        java.lang.String _sort_sortItem = "";
        com.dl.reporting.execution2005.SortDirectionEnum _sort_direction = null;
        boolean _sort_clear = false;
        com.dl.reporting.execution2005.ExecutionHeader _sort_executionHeader = null;
        com.dl.reporting.execution2005.TrustedUserHeader _sort_trustedUserHeader = null;
        javax.xml.ws.Holder<java.lang.Integer> _sort_pageNumber = new javax.xml.ws.Holder<java.lang.Integer>();
        javax.xml.ws.Holder<java.lang.String> _sort_reportItem = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<java.lang.Integer> _sort_numPages = new javax.xml.ws.Holder<java.lang.Integer>();
        javax.xml.ws.Holder<com.dl.reporting.execution2005.ServerInfoHeader> _sort_serverInfoHeader = new javax.xml.ws.Holder<com.dl.reporting.execution2005.ServerInfoHeader>();
        port.sort(_sort_sortItem, _sort_direction, _sort_clear, _sort_executionHeader, _sort_trustedUserHeader, _sort_pageNumber, _sort_reportItem, _sort_numPages, _sort_serverInfoHeader);

        System.out.println("sort._sort_pageNumber=" + _sort_pageNumber.value);
        System.out.println("sort._sort_reportItem=" + _sort_reportItem.value);
        System.out.println("sort._sort_numPages=" + _sort_numPages.value);
        System.out.println("sort._sort_serverInfoHeader=" + _sort_serverInfoHeader.value);

        }
        {
        System.out.println("Invoking loadReportDefinition2...");
        byte[] _loadReportDefinition2_definition = new byte[0];
        com.dl.reporting.execution2005.TrustedUserHeader _loadReportDefinition2_trustedUserHeader = null;
        javax.xml.ws.Holder<com.dl.reporting.execution2005.ExecutionInfo2> _loadReportDefinition2_executionInfo = new javax.xml.ws.Holder<com.dl.reporting.execution2005.ExecutionInfo2>();
        javax.xml.ws.Holder<com.dl.reporting.execution2005.ArrayOfWarning> _loadReportDefinition2_warnings = new javax.xml.ws.Holder<com.dl.reporting.execution2005.ArrayOfWarning>();
        javax.xml.ws.Holder<com.dl.reporting.execution2005.ExecutionHeader> _loadReportDefinition2_executionHeader = new javax.xml.ws.Holder<com.dl.reporting.execution2005.ExecutionHeader>();
        javax.xml.ws.Holder<com.dl.reporting.execution2005.ServerInfoHeader> _loadReportDefinition2_serverInfoHeader = new javax.xml.ws.Holder<com.dl.reporting.execution2005.ServerInfoHeader>();
        port.loadReportDefinition2(_loadReportDefinition2_definition, _loadReportDefinition2_trustedUserHeader, _loadReportDefinition2_executionInfo, _loadReportDefinition2_warnings, _loadReportDefinition2_executionHeader, _loadReportDefinition2_serverInfoHeader);

        System.out.println("loadReportDefinition2._loadReportDefinition2_executionInfo=" + _loadReportDefinition2_executionInfo.value);
        System.out.println("loadReportDefinition2._loadReportDefinition2_warnings=" + _loadReportDefinition2_warnings.value);
        System.out.println("loadReportDefinition2._loadReportDefinition2_executionHeader=" + _loadReportDefinition2_executionHeader.value);
        System.out.println("loadReportDefinition2._loadReportDefinition2_serverInfoHeader=" + _loadReportDefinition2_serverInfoHeader.value);

        }
        {
        System.out.println("Invoking resetExecution...");
        com.dl.reporting.execution2005.ExecutionHeader _resetExecution_executionHeader = null;
        com.dl.reporting.execution2005.TrustedUserHeader _resetExecution_trustedUserHeader = null;
        javax.xml.ws.Holder<com.dl.reporting.execution2005.ServerInfoHeader> _resetExecution_serverInfoHeader = new javax.xml.ws.Holder<com.dl.reporting.execution2005.ServerInfoHeader>();
        com.dl.reporting.execution2005.ExecutionInfo _resetExecution__return = port.resetExecution(_resetExecution_executionHeader, _resetExecution_trustedUserHeader, _resetExecution_serverInfoHeader);
        System.out.println("resetExecution.result=" + _resetExecution__return);

        System.out.println("resetExecution._resetExecution_serverInfoHeader=" + _resetExecution_serverInfoHeader.value);

        }
        {
        System.out.println("Invoking setExecutionCredentials...");
        com.dl.reporting.execution2005.ArrayOfDataSourceCredentials _setExecutionCredentials_credentials = null;
        com.dl.reporting.execution2005.ExecutionHeader _setExecutionCredentials_executionHeader = null;
        com.dl.reporting.execution2005.TrustedUserHeader _setExecutionCredentials_trustedUserHeader = null;
        javax.xml.ws.Holder<com.dl.reporting.execution2005.ServerInfoHeader> _setExecutionCredentials_serverInfoHeader = new javax.xml.ws.Holder<com.dl.reporting.execution2005.ServerInfoHeader>();
        com.dl.reporting.execution2005.ExecutionInfo _setExecutionCredentials__return = port.setExecutionCredentials(_setExecutionCredentials_credentials, _setExecutionCredentials_executionHeader, _setExecutionCredentials_trustedUserHeader, _setExecutionCredentials_serverInfoHeader);
        System.out.println("setExecutionCredentials.result=" + _setExecutionCredentials__return);

        System.out.println("setExecutionCredentials._setExecutionCredentials_serverInfoHeader=" + _setExecutionCredentials_serverInfoHeader.value);

        }
        {
        System.out.println("Invoking getExecutionInfo3...");
        com.dl.reporting.execution2005.ExecutionHeader _getExecutionInfo3_executionHeader = null;
        com.dl.reporting.execution2005.TrustedUserHeader _getExecutionInfo3_trustedUserHeader = null;
        javax.xml.ws.Holder<com.dl.reporting.execution2005.ServerInfoHeader> _getExecutionInfo3_serverInfoHeader = new javax.xml.ws.Holder<com.dl.reporting.execution2005.ServerInfoHeader>();
        com.dl.reporting.execution2005.ExecutionInfo3 _getExecutionInfo3__return = port.getExecutionInfo3(_getExecutionInfo3_executionHeader, _getExecutionInfo3_trustedUserHeader, _getExecutionInfo3_serverInfoHeader);
        System.out.println("getExecutionInfo3.result=" + _getExecutionInfo3__return);

        System.out.println("getExecutionInfo3._getExecutionInfo3_serverInfoHeader=" + _getExecutionInfo3_serverInfoHeader.value);

        }
        {
        System.out.println("Invoking getExecutionInfo2...");
        com.dl.reporting.execution2005.ExecutionHeader _getExecutionInfo2_executionHeader = null;
        com.dl.reporting.execution2005.TrustedUserHeader _getExecutionInfo2_trustedUserHeader = null;
        javax.xml.ws.Holder<com.dl.reporting.execution2005.ServerInfoHeader> _getExecutionInfo2_serverInfoHeader = new javax.xml.ws.Holder<com.dl.reporting.execution2005.ServerInfoHeader>();
        com.dl.reporting.execution2005.ExecutionInfo2 _getExecutionInfo2__return = port.getExecutionInfo2(_getExecutionInfo2_executionHeader, _getExecutionInfo2_trustedUserHeader, _getExecutionInfo2_serverInfoHeader);
        System.out.println("getExecutionInfo2.result=" + _getExecutionInfo2__return);

        System.out.println("getExecutionInfo2._getExecutionInfo2_serverInfoHeader=" + _getExecutionInfo2_serverInfoHeader.value);

        }
        {
        System.out.println("Invoking renderStream...");
        java.lang.String _renderStream_format = "";
        java.lang.String _renderStream_streamID = "";
        java.lang.String _renderStream_deviceInfo = "";
        com.dl.reporting.execution2005.ExecutionHeader _renderStream_executionHeader = null;
        com.dl.reporting.execution2005.TrustedUserHeader _renderStream_trustedUserHeader = null;
        javax.xml.ws.Holder<byte[]> _renderStream_result = new javax.xml.ws.Holder<byte[]>();
        javax.xml.ws.Holder<java.lang.String> _renderStream_encoding = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<java.lang.String> _renderStream_mimeType = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<com.dl.reporting.execution2005.ServerInfoHeader> _renderStream_serverInfoHeader = new javax.xml.ws.Holder<com.dl.reporting.execution2005.ServerInfoHeader>();
        port.renderStream(_renderStream_format, _renderStream_streamID, _renderStream_deviceInfo, _renderStream_executionHeader, _renderStream_trustedUserHeader, _renderStream_result, _renderStream_encoding, _renderStream_mimeType, _renderStream_serverInfoHeader);

        System.out.println("renderStream._renderStream_result=" + _renderStream_result.value);
        System.out.println("renderStream._renderStream_encoding=" + _renderStream_encoding.value);
        System.out.println("renderStream._renderStream_mimeType=" + _renderStream_mimeType.value);
        System.out.println("renderStream._renderStream_serverInfoHeader=" + _renderStream_serverInfoHeader.value);

        }

        System.exit(0);
    }

}
